import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { registerSW } from 'virtual:pwa-register';
import * as Sentry from '@sentry/react';
import App from './App.jsx';
import ErrorBoundary from './components/ErrorBoundary.jsx';
import { supabase } from './lib/supabase.js';
import './index.css';

// Production error monitoring. Sentry DSN (publishable, ships in the client
// bundle); absent in dev = no noise. Error capture only: no tracing, no replay.
if (import.meta.env.PROD && import.meta.env.VITE_SENTRY_DSN) {
  Sentry.init({ dsn: import.meta.env.VITE_SENTRY_DSN });
}

let swReg = null;
// update() rejects if the fetch of sw.js fails (intermittent network): the error is
// swallowed — there is nothing to do, and it retries on the next check. Without the
// catch = noise in Sentry.
const check = () => swReg?.update().catch(() => {}); // checks whether a new sw.js exists

// The sw.js generated by vite-plugin-pwa does NOT perform skipWaiting on its own: it ships
// a listener that waits for a 'SKIP_WAITING' message (and with injectRegister:false nobody
// sends it). Without that, the new SW stays in 'waiting', the old one keeps controlling and
// serves the previous bundle — hence "I don't see the change" after deploying. onRegisteredSW
// (below) activates the new SW; when it takes control (controllerchange) we reload once to
// load the new JS. The 1st installation (no previous controller) is skipped so the first
// visit does not reload.
if ('serviceWorker' in navigator) {
  const hadController = !!navigator.serviceWorker.controller;
  let refreshing = false;
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (refreshing || !hadController) return;
    refreshing = true;
    window.location.reload();
  });
}

registerSW({
  immediate: true,
  onRegisteredSW(_url, r) {
    swReg = r;
    if (!r) return;
    // Activates the new SW (sw.js listens for 'SKIP_WAITING'): on startup if one was
    // already waiting, and when a new one installs while a controller already exists
    // (= it is an update).
    const skip = () => r.waiting?.postMessage({ type: 'SKIP_WAITING' });
    skip();
    r.addEventListener('updatefound', () => {
      const nw = r.installing;
      nw?.addEventListener('statechange', () => {
        if (nw.state === 'installed' && navigator.serviceWorker.controller) skip();
      });
    });
    setInterval(check, 60 * 60 * 1000); // long-lived open session: checks for a deploy every hour
  },
});

// Opening / bringing the app to the foreground
document.addEventListener('visibilitychange', () => {
  if (document.visibilityState === 'visible') check();
});
// Regaining connectivity (mobile device that was offline)
window.addEventListener('online', check);
// Login
supabase.auth.onAuthStateChange((event) => {
  if (event === 'SIGNED_IN') check();
});

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <ErrorBoundary>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </ErrorBoundary>
  </StrictMode>
);
